"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_blue)\
$os\
$username\
[](bg:color_yellow fg:color_blue)\
$directory\
$package\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_aqua)\
$aws\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$lua\
$kotlin\
$haskell\
$python\
[](fg:color_aqua bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
$shlvl\
$cmd_duration\
$jobs\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

# # Color palettes config
[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.gruvbox_dark_custom]
color_fg0 = "#ebdbb2"
color_fg1 = "#282828"
color_bg3 = "#928374"
color_blue = "#83a598"
color_aqua = "#8ec07c"
color_green = "#b8bb26"
color_orange = "#fe8019"
color_purple = "#d3869b"
color_red = "#fb4934"
color_yellow = "#fabd2f"

[palettes.gruvbox_light]
color_fg0 = "#fbf1c7"
color_bg1 = "#928374"
color_bg3 = "#9d0006"
color_blue = "#79740e"
color_aqua = "#b57614"
color_green = "#076678"
color_orange = "#8f3f71"
color_purple = "#427b58"
color_red = "#3c3836"
color_yellow = "#af3a03"

[os]
disabled = false
style = "bg:color_blue fg:color_fg0"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
FreeBSD = ""
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
openSUSE = ""
Pop = ""
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Unknown = "?"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_blue fg:color_fg0"
format = '[ $user ]($style)'

[directory]
read_only = ""
style = "fg:color_fg0 bg:color_yellow"
format = '[ $read_only$path]($style)'
truncate_to_repo = true                # truncates directory to root folder if in github repo
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Desktop" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"projects" = "󰲋 "
"Sync" = " "
"Videos" = "  "
"Public" = "󰒋 "
"Templates" = "󰈏 "
[package]
style = "fg:color_fg0 bg:color_yellow"
format = '[ |${symbol}(${version})]($style)'
symbol = "📦"


[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch(:$remote_branch) ](fg:color_fg0 bg:color_aqua)]($style)'
truncation_length = 15
truncation_symbol = "…"

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

# [git_metrics]
# format = "([+$added]($added_style))([-$deleted]($deleted_style))"
# added_style = "gray"
# deleted_style = "red"
# disabled = false

[aws]
symbol = ""
style = "fg:aqua bg:bg"


[nodejs]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
version_format = '${raw}'

[c]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[cpp]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[lua]
symbol = ''
version_format = '${raw}'
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'
style = "fg:aqua bg:bg"

[rust]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[golang]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[php]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[java]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[kotlin]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[haskell]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
# pyenv_version_name = true
pyenv_prefix = "venv"
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
style = "bg:color_aqua"
detect_extensions = ["py"]
format = '[[ $symbol( $version)(\($virtualenv\)) ](fg:color_fg0 bg:color_aqua)]($style)'
version_format = "${raw}"

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
only_with_files = true
detect_files = [
  "docker-compose.yml",
  "docker-compose.yaml",
  "compose.yml",
  "compose.yaml",
  "Dockerfile",
]
detect_folders = []
disabled = false

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
min_time = 1_500
show_milliseconds = false
format = '[[ 󱦟$duration ](fg:color_fg0 bg:color_bg1)]($style)'
style = "color_bblue"
show_notifications = false
min_time_to_notify = 50_000

[shlvl]
format = '[[ $shlvl ](fg:color_fg0 bg:color_bg1)]($style)'
threshold = 2
symbol = ""
disabled = false
style = "bg:color_bg1"

[jobs]
symbol_threshold = 1
number_threshold = 2
format = '[[  $number ](fg:color_fg0 bg:color_bg1)]($style)'
style = "bg:color_bg1"
disabled = false
